# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : cloner le depot
    - uses : actions/checkout@v3
    - name : installer Pyhon 3.10
    - uses: actions/checkout@v4
      with:
        python-version: "3.10"
    - name: Install les dépendances 
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lancer les tests
      run: |
        export PYTHONPATH=$PYTHONPATH:./src
        pytest tests/

